# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-24 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0003_staffnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffnew',
            name='email',
            field=models.EmailField(max_length=125, unique=True),
        ),
    ]
