# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-24 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0005_auto_20160824_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffnew',
            name='counter',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='staffnew',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
