# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-24 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0006_auto_20160824_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffnew',
            name='bank_id',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='staffnew',
            name='user_id',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='staffnew',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
