# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0007_auto_20160824_1753'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffUser',
        ),
    ]
